### ISSUE TITLE
Zip file with directory structure

### ISSUE THREAD

**Issue by aaltat** [bulkan/robotframework-archivelibrary#12]
Ugh

If I have zip file which has subfolders and files in it. In some cases the ArchiveLibrary is not able to extract the zip file correctly. This seems be related that if I do this: 
```
zf = zipfile.ZipFile(zfile)
print zf.namelist()
```
It will only print the files. Example: 
```
['path1/file1.txt', 'path1/file2.txt', ...] 
```
The archive library seems to expect that also paths are also included in the zf.namelist(). Example: 
```
['path1', 'path1/file1.txt', 'path1/file2.txt', ...] 
```

But one create zip file with -no-dir-entries [1] flag in Linux and then the print zf.namelist() will only list the paths to files and zip file does not contain directory entries. Then the ArchiveLibrary fill fail on this stack trace: 
```
DEBUG 	Traceback (most recent call last): File "C:\Python27\lib\site-packages\ArchiveLibrary\keywords.py", line 43, in extract_zip_file unzipper.extract(zfile, dest) File "C:\Python27\lib\site-packages\ArchiveLibrary\utils.py", line 41, in extract outfile = open(os.path.join(dest, name), 'wb'
```

[1]http://linux.die.net/man/1/zip

**Comment by bulkan** [comment]
Pull requests welcome. :+1:

**Comment by aaltat** [comment]
Could do that. There is question though: 
By looking the code and looking the python ZipFile documentation, is there are reason why the ZipFile.extractall() function is not used to extract the archive?

**Comment by bulkan** [comment]
There probably was a reason but its [been so long that I dont remember](a6c6da94f06f71995ae3e181848c5d0eaac27597)

**Comment by aaltat** [comment]
If the acceptance tests pass, would you accept a pull request that would change to code to use the ZipFile.extractall()?

**Comment by bulkan** [comment]
I sure will accept a PR if the tests pass.

**Comment by aaltat** [comment]
When trying to looking the issue with fresh eyes, I can not reproduce the issue. Closing.
