### ISSUE TITLE
Keyword documentation is not updated

### ISSUE THREAD

**Issue by aaltat** [bulkan/robotframework-archivelibrary#16]
The latest version contains new keywords which are not visible in the library documentation: http://bulkan.github.io/robotframework-archivelibrary/

**Comment by bulkan** [comment]
Thanks. Pull requests welcome :)

**Comment by aaltat** [comment]
Would be easy to do, but there is not instructions where the generated doc should go...

**Comment by aaltat** [comment]
@bulkan: Are you still looking a maintainer? If you are, I can do it.

**Comment by vkosuri** [comment]
keyword documentation is hosted using github pages so instead of trying to merge this into master the PR should be to merge into the gh-pages branch

**Comment by vkosuri** [comment]
PR  https://github.com/bulkan/robotframework-archivelibrary/pull/22 merged into master hence closing this issue.
