### ISSUE TITLE
extracting the archives on osx without specifying the destination folder fails

### ISSUE THREAD

**Issue by slash777** [bulkan/robotframework-archivelibrary#17]
Extract Tar File    my_archive.tar.gz

fails with error: AttributeError: 'NoneType' object has no attribute 'endswith'

Workaround: 1. specify destination path, e.g:
Extract Tar File    my_archive.tar.gz    .

**Comment by vkosuri** [comment]
The problem default current directory value overwritten by extract_tar_file

``` Python
def extract_tar_file(self, tfile, dest=None):
        ''' Extract a TAR file

        `tfile` the path to the TAR file

        `dest` optional destination folder. It will be created if It doesn't exist.
        '''
        if dest:
            self.oslib.create_directory(dest)
        else:
            dest = "."
            
        self.oslib.file_should_exist(tfile)

        untarrer = Untar()
        untarrer.extract(tfile, dest)
```

None is overwriting default dest options in utils.py

``` Python
def extract(self, tfile, dest="."):
        if not dest.endswith(':') and not os.path.exists(dest):
            os.makedirs(dest)
```

@bulkan can i submit PR?

**Comment by bulkan** [comment]
yes you can

**Comment by vkosuri** [comment]
@slash777 can you verify with latest changes?

**Comment by vkosuri** [comment]
@slash777 any updates on this issue?

**Comment by vkosuri** [comment]
No response from @slash777 hence closing this issue
