### ISSUE TITLE
7z and rar file support

### ISSUE THREAD

**Issue by vkosuri** [bulkan/robotframework-archivelibrary#19]
This requires fallowing packages should be install

``` shell
pip install --upgrade pylzma
pip install --upgrade rarfile
```

@bulkan can I go with?

**Comment by bulkan** [comment]
@vkosuri sure you can just add some tests too :) 

Also I've made you a collaborator of this repo but please submit PR's instead of pushing directly to `master`

**Comment by vkosuri** [comment]
@thank you and sure i will submit PRs for any now and future issues

**Comment by vkosuri** [comment]
rar files requires Unrar.dll files, looking for other options
```
raise RarCannotExec("Unrar not installed? (rarfile.UNRAR_TOOL=%r)" % UNRAR_TOOL
``

**Comment by vkosuri** [comment]
@bulkan for 7z and rar It relies on helper applications to handle those archive formats (for example 7zip for 7zip archives).

can we go with this? If so, we have to verify these programs are installed on Travis also?

**Comment by vkosuri** [comment]
@bulkan any comments?

**Comment by bulkan** [comment]
This probably wont work in travis.

**Comment by vkosuri** [comment]
then will go with only keywords without testcases, or we could skip this feature?

**Comment by bulkan** [comment]
best skip the feature until someone else reallt needs it.

**Comment by vkosuri** [comment]
Yep, Thank you @bulkan
