### ISSUE TITLE
Can't install this library with python 3.4

### ISSUE THREAD

**Issue by jchabrol** [bulkan/robotframework-archivelibrary#23]
Hi, 

i use python 3 and when I try to make a:
pip install robotframework-archivelibrary

I got an error.

File "<string>", line 17, in <module>
      File "/home/certivibe/test/build/robotframework-archivelibrary/setup.py", line 8, in <module>
        execfile(join(dirname(abspath(__file__)), 'ArchiveLibrary', 'version.py'))
    NameError: name 'execfile' is not defined
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/certivibe/test/build/robotframework-archivelibrary/setup.py", line 8, in <module>

    execfile(join(dirname(abspath(__file__)), 'ArchiveLibrary', 'version.py'))

NameError: name 'execfile' is not defined

**Comment by vkosuri** [comment]
@jchabrol It's problem ``python 3.x`` doesn't support ``execfile``.   I think you are using Linux enviroment, then I would recommand you to use ``python 2.7 virtualenv``.  Because ``robotframework`` still doesn't support many functionalities on ``python 3.x``

A more information guide to create virutalenv fallow this guide http://docs.python-guide.org/en/latest/dev/virtualenvs/

**Comment by jchabrol** [comment]
Hi,

I've seen that python3 didn't support execfile anymore.
I see that robotframewwork support python3 but I haven't seen too much restriction regarding the support of python3 by robot.
So one of my nightmare with python 2.7 is the unicode... as it was easyer with python3...

regards

jerome

**Comment by vkosuri** [comment]
@bulkan any comments on this?

**Comment by bulkan** [comment]
This https://github.com/bulkan/robotframework-archivelibrary/blob/master/setup.py#L8 needs to be updated to support 3.

I don't have time to do that. 

Pull requests welcome.

**Comment by jchabrol** [comment]
Hello,

I have something to be checked but I can't push my branche.
I use six library  to allow compatilibity between python 2 and 3.

but I have to test the pip install is it possible to do that with a branche on github ?

regards,

Jerome

**Comment by vkosuri** [comment]
@jchabrol something could help you http://stackoverflow.com/questions/20101834/pip-install-from-github-repo-branch

**Comment by vkosuri** [comment]
@jchabrol can you verify with master branch?

**Comment by jchabrol** [comment]
Yes it works fine thanks.

**Comment by vkosuri** [comment]
@jchabrol thank you
