### ISSUE TITLE
Archivelibrary should actually compress when creating zip

### ISSUE THREAD

**Issue by hpschry** [bulkan/robotframework-archivelibrary#31]
With the current implementation files will be only stored in zip files but not compressed. The zipfile.ZIP_DEFLATED option will be required to enable compression.

**Comment by bulkan** [comment]
@hpschry Pull Requests welcome :)

**Comment by hpschry** [comment]
There it is!

**Comment by thomasmoon** [comment]
Hi guys, this compression option is great! I notice it was merged, but never published with the official package, why not?

**Comment by lucagiove** [comment]
I'll have a look

**Comment by lucagiove** [comment]
@bulkan could you transfer the lib to @MarketSquare ?
I'd like to add PyPi token and migrate the pipelines to GitHub Actions I've scheduled a Meetup the next 20 of May to do some livecoding on this library together with the Italian RF community.

Thanks!

**Comment by lucagiove** [comment]
@thomasmoon new version should be available in PyPi now, please let me know whether it works!

> @bulkan could you transfer the lib to @MarketSquare ?
> I'd like to add PyPi token and migrate the pipelines to GitHub Actions I've scheduled a Meetup the next 20 of May to do some livecoding on this library together with the Italian RF community.
> 
> Thanks!

@bulkan please, I need it also in order to add CodeCov and setup github pages

**Comment by bulkan** [comment]
@lucagiove it's done now
